AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - 'docker/**/*'
    - 'cypress/**/*'
  TargetRubyVersion: 2.7
  DisplayCopNames: true

Style/AsciiComments:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'spec/**/*'

Style/AccessModifierDeclarations:
  Enabled: false

Metrics/AbcSize:
  Max: 90

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'lib/rakes/**/*'

Layout/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 60
  Exclude:

Metrics/ModuleLength:
  Max: 300

Metrics/PerceivedComplexity:
  Max: 11

Metrics/BlockLength:
  Max: 60
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/**/*'

Naming/MethodParameterName:
  MinNameLength: 2

Style/FrozenStringLiteralComment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: false

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/AccessorGrouping:
  Enabled: false

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/FormatStringToken:
  Exclude:
    - 'admin/app/helpers/admin/path_helper.rb'
